-- Phase 4A: seed canonique du quiz genere depuis assets/js/quiz-data.js.
-- Ne pas modifier manuellement: npm run generate:quiz-seed.

truncate table private.quiz_answers restart identity cascade;
delete from private.quiz_categories;

insert into private.quiz_categories (id, title, description, duration_seconds, is_active, display_order)
values
  ('series', '📺 Séries TV - Top 20 des légendes', 'Top 20 des légendes du petit écran (20 personnages)', 600, true, 1),
  ('films', '🎬 Cinéma - Top 20 des icônes', 'Top 20 des icônes du 7ème art (20 personnages)', 600, true, 2),
  ('animeCelebres', '🌍 Anime/Manga - Top 30 des plus célèbres au monde', 'Top 30 des plus célèbres au monde (30 personnages)', 600, true, 3),
  ('animeDeteste', '💀 Anime/Manga - Top 20 des plus détestés', 'Top 20 des plus détestés (20 personnages)', 600, true, 4),
  ('animeForts', '🌌 Anime/Manga - Top 20 des plus puissants (Version Ultime)', 'Top 20 des plus puissants (version ultime) (20 personnages)', 600, true, 5),
  ('animeIntelligents', '🧠 Anime/Manga - Top 15 des génies ultimes', 'Top 15 des génies ultimes (15 personnages)', 600, true, 6),
  ('sportsMusique', '⚽🏀🎵 Sports & Musique - Top 40 des stars mondiales', 'Top 40 des stars mondiales (40 célébrités)', 600, true, 7),
  ('seriesDeteste', '👎 Séries TV - Top 10 des plus détestés', 'Top 10 des personnages détestés (10 personnages)', 600, true, 8),
  ('fillesPuissantes', '👸 Anime/Manga - Top 15 des filles les plus puissantes', 'Top 15 des filles les plus puissantes (15 personnages)', 600, true, 9),
  ('meilleursFootballeurs', '⚽ Football - Top 15 des meilleurs joueurs de tous les temps', 'Top 15 des meilleurs joueurs de tous les temps (15 joueurs)', 600, true, 10),
  ('meilleursEntraineurs', '📋 Football - Top 10 des meilleurs entraîneurs de tous les temps', 'Top 10 des meilleurs entraîneurs de tous les temps (10 entraîneurs)', 600, true, 11),
  ('meilleursMangas', '📖 Mangas - Top 15 des meilleurs mangas de tous les temps', 'Top 15 des meilleurs mangas de tous les temps (15 mangas)', 600, true, 12),
  ('meilleursAnimes', '🎬 Animes - Top 15 des meilleurs animes de tous les temps', 'Top 15 des meilleurs animes de tous les temps (15 animes)', 600, true, 13),
  ('animeIdiots', '🤪 Anime/Manga - Top 10 des personnages les plus idiots', 'Top 10 des personnages les plus idiots (10 personnages)', 600, true, 14),
  ('meilleursCombats', '⚔️ Anime/Manga - Top 20 des meilleurs combats (tapez le nom avec ''vs'')', 'Top 20 des meilleurs combats all time (20 combats)', 600, true, 15),
  ('meilleursArcs', '📖 Anime/Manga - Top 10 des meilleurs arcs', 'Top 10 des meilleurs arcs (10 arcs)', 600, true, 16),
  ('meilleuresTechniques', '✨ Anime/Manga - Top 10 des meilleures techniques', 'Top 10 des meilleures techniques (10 techniques)', 600, true, 17),
  ('meilleuresTransformations', '🔄 Anime/Manga - Top 10 des meilleures transformations', 'Top 10 des meilleures transformations (10 transformations)', 600, true, 18),
  ('ligueDesChampions', '🏆 Ligue des Champions - Vainqueurs de 2000 à 2026', 'Vainqueurs de 2000 à 2026 (27 clubs)', 600, true, 19),
  ('ballonDor', '🥇 Ballon d''Or - Vainqueurs de 2000 à 2025', 'Vainqueurs de 2000 à 2025 (25 joueurs)', 600, true, 20),
  ('jeuxVideo', '🎮 Légendes du Jeu Vidéo - Top 10 des jeux cultes', 'Top 10 des jeux cultes (10 jeux)', 600, true, 21),
  ('superHeros', '🦸 Super-héros Marvel & DC - Top 20', 'Top 20 des héros et vilains (20 personnages)', 600, true, 22),
  ('rapFrUs', '🎤 Rap Français & US - Top 15 des légendes', 'Top 15 des plus grandes légendes (15 artistes)', 600, true, 23),
  ('trouveAnime', '🔍 Trouve l''Anime (Emojis)', 'Trouve l''anime grâce aux emojis ! (15 animes)', 600, true, 24),
  ('devinePersonnage', '🎭 Devine le Personnage (Indices)', 'Trouve le personnage grâce à l''indice (20 personnages)', 600, true, 25),
  ('animeParOrganisation', '🏛️ Anime par Organisation', 'Trouve l''anime de l''organisation (9 organisations)', 600, true, 26);

insert into private.quiz_answers (category_id, answer_text, answer_normalized, hint, answer_year, display_order)
values
  ('series', 'Walter White', 'walter white', null, null, 1),
  ('series', 'Jon Snow', 'jon snow', null, null, 2),
  ('series', 'Daenerys Targaryen', 'daenerys targaryen', null, null, 3),
  ('series', 'Sherlock Holmes', 'sherlock holmes', null, null, 4),
  ('series', 'Rick Grimes', 'rick grimes', null, null, 5),
  ('series', 'Michael Scott', 'michael scott', null, null, 6),
  ('series', 'Tyrion Lannister', 'tyrion lannister', null, null, 7),
  ('series', 'Eleven', 'eleven', null, null, 8),
  ('series', 'Wednesday Addams', 'wednesday addams', null, null, 9),
  ('series', 'Joey Tribbiani', 'joey tribbiani', null, null, 10),
  ('series', 'Gregory House', 'gregory house', null, null, 11),
  ('series', 'Dexter Morgan', 'dexter morgan', null, null, 12),
  ('series', 'Don Draper', 'don draper', null, null, 13),
  ('series', 'Carrie Bradshaw', 'carrie bradshaw', null, null, 14),
  ('series', 'Tony Soprano', 'tony soprano', null, null, 15),
  ('series', 'Loki', 'loki', null, null, 16),
  ('series', 'Geralt de Riv', 'geralt de riv', null, null, 17),
  ('series', 'Elliot Alderson', 'elliot alderson', null, null, 18),
  ('series', 'Klaus Hargreeves', 'klaus hargreeves', null, null, 19),
  ('series', 'Joe Goldberg', 'joe goldberg', null, null, 20),
  ('films', 'Harry Potter', 'harry potter', null, null, 1),
  ('films', 'Luke Skywalker', 'luke skywalker', null, null, 2),
  ('films', 'Jack Sparrow', 'jack sparrow', null, null, 3),
  ('films', 'James Bond', 'james bond', null, null, 4),
  ('films', 'Indiana Jones', 'indiana jones', null, null, 5),
  ('films', 'Forrest Gump', 'forrest gump', null, null, 6),
  ('films', 'John Wick', 'john wick', null, null, 7),
  ('films', 'Tony Stark', 'tony stark', null, null, 8),
  ('films', 'Peter Parker', 'peter parker', null, null, 9),
  ('films', 'Bruce Wayne', 'bruce wayne', null, null, 10),
  ('films', 'Ellen Ripley', 'ellen ripley', null, null, 11),
  ('films', 'Neo', 'neo', null, null, 12),
  ('films', 'Tyler Durden', 'tyler durden', null, null, 13),
  ('films', 'Michael Corleone', 'michael corleone', null, null, 14),
  ('films', 'Hannibal Lecter', 'hannibal lecter', null, null, 15),
  ('films', 'Joker', 'joker', null, null, 16),
  ('films', 'Willy Wonka', 'willy wonka', null, null, 17),
  ('films', 'Rocky Balboa', 'rocky balboa', null, null, 18),
  ('films', 'Ethan Hunt', 'ethan hunt', null, null, 19),
  ('films', 'John McClane', 'john mcclane', null, null, 20),
  ('animeCelebres', 'Son Goku', 'son goku', null, null, 1),
  ('animeCelebres', 'Naruto Uzumaki', 'naruto uzumaki', null, null, 2),
  ('animeCelebres', 'Monkey D. Luffy', 'monkey d luffy', null, null, 3),
  ('animeCelebres', 'Pikachu', 'pikachu', null, null, 4),
  ('animeCelebres', 'Sailor Moon', 'sailor moon', null, null, 5),
  ('animeCelebres', 'Ichigo Kurosaki', 'ichigo kurosaki', null, null, 6),
  ('animeCelebres', 'Eren Yeager', 'eren yeager', null, null, 7),
  ('animeCelebres', 'Light Yagami', 'light yagami', null, null, 8),
  ('animeCelebres', 'Levi Ackerman', 'levi ackerman', null, null, 9),
  ('animeCelebres', 'Sasuke Uchiha', 'sasuke uchiha', null, null, 10),
  ('animeCelebres', 'Vegeta', 'vegeta', null, null, 11),
  ('animeCelebres', 'Gojo Satoru', 'gojo satoru', null, null, 12),
  ('animeCelebres', 'Tanjiro Kamado', 'tanjiro kamado', null, null, 13),
  ('animeCelebres', 'Killua Zoldyck', 'killua zoldyck', null, null, 14),
  ('animeCelebres', 'Gon Freecss', 'gon freecss', null, null, 15),
  ('animeCelebres', 'Edward Elric', 'edward elric', null, null, 16),
  ('animeCelebres', 'Mikasa Ackerman', 'mikasa ackerman', null, null, 17),
  ('animeCelebres', 'Kakashi Hatake', 'kakashi hatake', null, null, 18),
  ('animeCelebres', 'Itachi Uchiha', 'itachi uchiha', null, null, 19),
  ('animeCelebres', 'Roronoa Zoro', 'roronoa zoro', null, null, 20),
  ('animeCelebres', 'Natsu Dragneel', 'natsu dragneel', null, null, 21),
  ('animeCelebres', 'Deku', 'deku', null, null, 22),
  ('animeCelebres', 'All Might', 'all might', null, null, 23),
  ('animeCelebres', 'Saitama', 'saitama', null, null, 24),
  ('animeCelebres', 'Ken Kaneki', 'ken kaneki', null, null, 25),
  ('animeCelebres', 'L', 'l', null, null, 26),
  ('animeCelebres', 'Ash Ketchum', 'ash ketchum', null, null, 27),
  ('animeCelebres', 'Alucard', 'alucard', null, null, 28),
  ('animeCelebres', 'Spike Spiegel', 'spike spiegel', null, null, 29),
  ('animeCelebres', 'Jotaro Kujo', 'jotaro kujo', null, null, 30),
  ('animeDeteste', 'Shou Tucker', 'shou tucker', null, null, 1),
  ('animeDeteste', 'Griffith', 'griffith', null, null, 2),
  ('animeDeteste', 'Danzo Shimura', 'danzo shimura', null, null, 3),
  ('animeDeteste', 'Rachel', 'rachel', null, null, 4),
  ('animeDeteste', 'Mahito', 'mahito', null, null, 5),
  ('animeDeteste', 'Sakura Haruno', 'sakura haruno', null, null, 6),
  ('animeDeteste', 'Mineta', 'mineta', null, null, 7),
  ('animeDeteste', 'Gabi Braun', 'gabi braun', null, null, 8),
  ('animeDeteste', 'Akainu', 'akainu', null, null, 9),
  ('animeDeteste', 'Blackbeard', 'blackbeard', null, null, 10),
  ('animeDeteste', 'Frieza', 'frieza', null, null, 11),
  ('animeDeteste', 'Kazuya Kinoshita', 'kazuya kinoshita', null, null, 12),
  ('animeDeteste', 'Makima', 'makima', null, null, 13),
  ('animeDeteste', 'Orochimaru', 'orochimaru', null, null, 14),
  ('animeDeteste', 'Envy', 'envy', null, null, 15),
  ('animeDeteste', 'Sugou Nobuyuki', 'sugou nobuyuki', null, null, 16),
  ('animeDeteste', 'Yukiteru Amano', 'yukiteru amano', null, null, 17),
  ('animeDeteste', 'Shinji Ikari', 'shinji ikari', null, null, 18),
  ('animeDeteste', 'Near', 'near', null, null, 19),
  ('animeDeteste', 'Malty Melromarc', 'malty melromarc', null, null, 20),
  ('animeForts', 'Featherine Augustus Aurora', 'featherine augustus aurora', null, null, 1),
  ('animeForts', 'The Creator', 'the creator', null, null, 2),
  ('animeForts', 'Lambdadelta', 'lambdadelta', null, null, 3),
  ('animeForts', 'Bernkastel', 'bernkastel', null, null, 4),
  ('animeForts', 'Akuto Sai', 'akuto sai', null, null, 5),
  ('animeForts', 'Zeno', 'zeno', null, null, 6),
  ('animeForts', 'Ren Fuji', 'ren fuji', null, null, 7),
  ('animeForts', 'Mercurius', 'mercurius', null, null, 8),
  ('animeForts', 'Madoka Kaname', 'madoka kaname', null, null, 9),
  ('animeForts', 'Akemi Homura', 'akemi homura', null, null, 10),
  ('animeForts', 'Othinus', 'othinus', null, null, 11),
  ('animeForts', 'Kami Tenchi', 'kami tenchi', null, null, 12),
  ('animeForts', 'Rimuru Tempest', 'rimuru tempest', null, null, 13),
  ('animeForts', 'Anos Voldigoad', 'anos voldigoad', null, null, 14),
  ('animeForts', 'Altair', 'altair', null, null, 15),
  ('animeForts', 'Medaka Kurokami', 'medaka kurokami', null, null, 16),
  ('animeForts', 'Ajimu Najimi', 'ajimu najimi', null, null, 17),
  ('animeForts', 'Ryougi Shiki', 'ryougi shiki', null, null, 18),
  ('animeForts', 'Sailor Cosmos', 'sailor cosmos', null, null, 19),
  ('animeForts', 'Haruhi Suzumiya', 'haruhi suzumiya', null, null, 20),
  ('animeIntelligents', 'Light Yagami', 'light yagami', null, null, 1),
  ('animeIntelligents', 'L', 'l', null, null, 2),
  ('animeIntelligents', 'Johan Liebert', 'johan liebert', null, null, 3),
  ('animeIntelligents', 'Lelouch Lamperouge', 'lelouch lamperouge', null, null, 4),
  ('animeIntelligents', 'Sosuke Aizen', 'sosuke aizen', null, null, 5),
  ('animeIntelligents', 'Ayanokoji Kiyotaka', 'ayanokoji kiyotaka', null, null, 6),
  ('animeIntelligents', 'Kisuke Urahara', 'kisuke urahara', null, null, 7),
  ('animeIntelligents', 'Senku Ishigami', 'senku ishigami', null, null, 8),
  ('animeIntelligents', 'Itachi Uchiha', 'itachi uchiha', null, null, 9),
  ('animeIntelligents', 'Shikamaru Nara', 'shikamaru nara', null, null, 10),
  ('animeIntelligents', 'Armin Arlert', 'armin arlert', null, null, 11),
  ('animeIntelligents', 'Bulma', 'bulma', null, null, 12),
  ('animeIntelligents', 'Kurisu Makise', 'kurisu makise', null, null, 13),
  ('animeIntelligents', 'Sora', 'sora', null, null, 14),
  ('animeIntelligents', 'Norman', 'norman', null, null, 15),
  ('sportsMusique', 'Lionel Messi', 'lionel messi', null, null, 1),
  ('sportsMusique', 'Cristiano Ronaldo', 'cristiano ronaldo', null, null, 2),
  ('sportsMusique', 'Neymar', 'neymar', null, null, 3),
  ('sportsMusique', 'Kylian Mbappe', 'kylian mbappe', null, null, 4),
  ('sportsMusique', 'Zinedine Zidane', 'zinedine zidane', null, null, 5),
  ('sportsMusique', 'David Beckham', 'david beckham', null, null, 6),
  ('sportsMusique', 'Ronaldinho', 'ronaldinho', null, null, 7),
  ('sportsMusique', 'Diego Maradona', 'diego maradona', null, null, 8),
  ('sportsMusique', 'Pele', 'pele', null, null, 9),
  ('sportsMusique', 'Karim Benzema', 'karim benzema', null, null, 10),
  ('sportsMusique', 'LeBron James', 'lebron james', null, null, 11),
  ('sportsMusique', 'Michael Jordan', 'michael jordan', null, null, 12),
  ('sportsMusique', 'Kobe Bryant', 'kobe bryant', null, null, 13),
  ('sportsMusique', 'Stephen Curry', 'stephen curry', null, null, 14),
  ('sportsMusique', 'Kevin Durant', 'kevin durant', null, null, 15),
  ('sportsMusique', 'Shaquille O''Neal', 'shaquille oneal', null, null, 16),
  ('sportsMusique', 'Magic Johnson', 'magic johnson', null, null, 17),
  ('sportsMusique', 'Larry Bird', 'larry bird', null, null, 18),
  ('sportsMusique', 'Giannis Antetokounmpo', 'giannis antetokounmpo', null, null, 19),
  ('sportsMusique', 'Allen Iverson', 'allen iverson', null, null, 20),
  ('sportsMusique', 'Serena Williams', 'serena williams', null, null, 21),
  ('sportsMusique', 'Roger Federer', 'roger federer', null, null, 22),
  ('sportsMusique', 'Rafael Nadal', 'rafael nadal', null, null, 23),
  ('sportsMusique', 'Mike Tyson', 'mike tyson', null, null, 24),
  ('sportsMusique', 'Muhammad Ali', 'muhammad ali', null, null, 25),
  ('sportsMusique', 'Usain Bolt', 'usain bolt', null, null, 26),
  ('sportsMusique', 'Michael Phelps', 'michael phelps', null, null, 27),
  ('sportsMusique', 'Tom Brady', 'tom brady', null, null, 28),
  ('sportsMusique', 'Tiger Woods', 'tiger woods', null, null, 29),
  ('sportsMusique', 'Simone Biles', 'simone biles', null, null, 30),
  ('sportsMusique', 'Michael Jackson', 'michael jackson', null, null, 31),
  ('sportsMusique', 'Beyonce', 'beyonce', null, null, 32),
  ('sportsMusique', 'Taylor Swift', 'taylor swift', null, null, 33),
  ('sportsMusique', 'Drake', 'drake', null, null, 34),
  ('sportsMusique', 'Eminem', 'eminem', null, null, 35),
  ('sportsMusique', 'Rihanna', 'rihanna', null, null, 36),
  ('sportsMusique', 'Justin Bieber', 'justin bieber', null, null, 37),
  ('sportsMusique', 'Ed Sheeran', 'ed sheeran', null, null, 38),
  ('sportsMusique', 'Ariana Grande', 'ariana grande', null, null, 39),
  ('sportsMusique', 'Kanye West', 'kanye west', null, null, 40),
  ('seriesDeteste', 'Joffrey Baratheon', 'joffrey baratheon', null, null, 1),
  ('seriesDeteste', 'Ramsay Bolton', 'ramsay bolton', null, null, 2),
  ('seriesDeteste', 'Dolores Umbridge', 'dolores umbridge', null, null, 3),
  ('seriesDeteste', 'Negan', 'negan', null, null, 4),
  ('seriesDeteste', 'Cersei Lannister', 'cersei lannister', null, null, 5),
  ('seriesDeteste', 'Geoffrey', 'geoffrey', null, null, 6),
  ('seriesDeteste', 'Petyr Baelish', 'petyr baelish', null, null, 7),
  ('seriesDeteste', 'The Night King', 'the night king', null, null, 8),
  ('seriesDeteste', 'White Walkers', 'white walkers', null, null, 9),
  ('seriesDeteste', 'Umbridge', 'umbridge', null, null, 10),
  ('fillesPuissantes', 'Featherine Augustus Aurora', 'featherine augustus aurora', null, null, 1),
  ('fillesPuissantes', 'Lambdadelta', 'lambdadelta', null, null, 2),
  ('fillesPuissantes', 'Bernkastel', 'bernkastel', null, null, 3),
  ('fillesPuissantes', 'Beatrice', 'beatrice', null, null, 4),
  ('fillesPuissantes', 'Madoka Kaname', 'madoka kaname', null, null, 5),
  ('fillesPuissantes', 'Akemi Homura', 'akemi homura', null, null, 6),
  ('fillesPuissantes', 'Haruhi Suzumiya', 'haruhi suzumiya', null, null, 7),
  ('fillesPuissantes', 'Altair', 'altair', null, null, 8),
  ('fillesPuissantes', 'Sailor Cosmos', 'sailor cosmos', null, null, 9),
  ('fillesPuissantes', 'Sailor Moon', 'sailor moon', null, null, 10),
  ('fillesPuissantes', 'Ryougi Shiki', 'ryougi shiki', null, null, 11),
  ('fillesPuissantes', 'Medaka Kurokami', 'medaka kurokami', null, null, 12),
  ('fillesPuissantes', 'Ajimu Najimi', 'ajimu najimi', null, null, 13),
  ('fillesPuissantes', 'Othinus', 'othinus', null, null, 14),
  ('fillesPuissantes', 'Kaguya Otsutsuki', 'kaguya otsutsuki', null, null, 15),
  ('meilleursFootballeurs', 'Lionel Messi', 'lionel messi', null, null, 1),
  ('meilleursFootballeurs', 'Pelé', 'pele', null, null, 2),
  ('meilleursFootballeurs', 'Diego Maradona', 'diego maradona', null, null, 3),
  ('meilleursFootballeurs', 'Cristiano Ronaldo', 'cristiano ronaldo', null, null, 4),
  ('meilleursFootballeurs', 'Johan Cruyff', 'johan cruyff', null, null, 5),
  ('meilleursFootballeurs', 'Zinedine Zidane', 'zinedine zidane', null, null, 6),
  ('meilleursFootballeurs', 'Ronaldo Nazário', 'ronaldo nazario', null, null, 7),
  ('meilleursFootballeurs', 'Michel Platini', 'michel platini', null, null, 8),
  ('meilleursFootballeurs', 'Franz Beckenbauer', 'franz beckenbauer', null, null, 9),
  ('meilleursFootballeurs', 'Alfredo Di Stéfano', 'alfredo di stefano', null, null, 10),
  ('meilleursFootballeurs', 'Ronaldinho', 'ronaldinho', null, null, 11),
  ('meilleursFootballeurs', 'Xavi Hernandez', 'xavi hernandez', null, null, 12),
  ('meilleursFootballeurs', 'Andrés Iniesta', 'andres iniesta', null, null, 13),
  ('meilleursFootballeurs', 'Paolo Maldini', 'paolo maldini', null, null, 14),
  ('meilleursFootballeurs', 'George Best', 'george best', null, null, 15),
  ('meilleursEntraineurs', 'Sir Alex Ferguson', 'sir alex ferguson', null, null, 1),
  ('meilleursEntraineurs', 'Pep Guardiola', 'pep guardiola', null, null, 2),
  ('meilleursEntraineurs', 'Rinus Michels', 'rinus michels', null, null, 3),
  ('meilleursEntraineurs', 'Arrigo Sacchi', 'arrigo sacchi', null, null, 4),
  ('meilleursEntraineurs', 'Carlo Ancelotti', 'carlo ancelotti', null, null, 5),
  ('meilleursEntraineurs', 'Johan Cruyff', 'johan cruyff', null, null, 6),
  ('meilleursEntraineurs', 'José Mourinho', 'jose mourinho', null, null, 7),
  ('meilleursEntraineurs', 'Viktor Maslov', 'viktor maslov', null, null, 8),
  ('meilleursEntraineurs', 'Valeriy Lobanovskyi', 'valeriy lobanovskyi', null, null, 9),
  ('meilleursEntraineurs', 'Vicente del Bosque', 'vicente del bosque', null, null, 10),
  ('meilleursMangas', 'One Piece', 'one piece', null, null, 1),
  ('meilleursMangas', 'Golgo 13', 'golgo 13', null, null, 2),
  ('meilleursMangas', 'Dragon Ball', 'dragon ball', null, null, 3),
  ('meilleursMangas', 'Naruto', 'naruto', null, null, 4),
  ('meilleursMangas', 'Detective Conan', 'detective conan', null, null, 5),
  ('meilleursMangas', 'Doraemon', 'doraemon', null, null, 6),
  ('meilleursMangas', 'Demon Slayer', 'demon slayer', null, null, 7),
  ('meilleursMangas', 'Jujutsu Kaisen', 'jujutsu kaisen', null, null, 8),
  ('meilleursMangas', 'Attack on Titan', 'attack on titan', null, null, 9),
  ('meilleursMangas', 'Slam Dunk', 'slam dunk', null, null, 10),
  ('meilleursMangas', 'Bleach', 'bleach', null, null, 11),
  ('meilleursMangas', 'Hunter x Hunter', 'hunter x hunter', null, null, 12),
  ('meilleursMangas', 'JoJo''s Bizarre Adventure', 'jojos bizarre adventure', null, null, 13),
  ('meilleursMangas', 'Fist of the North Star', 'fist of the north star', null, null, 14),
  ('meilleursMangas', 'Astro Boy', 'astro boy', null, null, 15),
  ('meilleursAnimes', 'Attack on Titan', 'attack on titan', null, null, 1),
  ('meilleursAnimes', 'Fullmetal Alchemist: Brotherhood', 'fullmetal alchemist brotherhood', null, null, 2),
  ('meilleursAnimes', 'One Piece', 'one piece', null, null, 3),
  ('meilleursAnimes', 'Hunter × Hunter', 'hunter  hunter', null, null, 4),
  ('meilleursAnimes', 'Death Note', 'death note', null, null, 5),
  ('meilleursAnimes', 'Naruto', 'naruto', null, null, 6),
  ('meilleursAnimes', 'Steins;Gate', 'steinsgate', null, null, 7),
  ('meilleursAnimes', 'Code Geass', 'code geass', null, null, 8),
  ('meilleursAnimes', 'Dragon Ball Z', 'dragon ball z', null, null, 9),
  ('meilleursAnimes', 'Bleach', 'bleach', null, null, 10),
  ('meilleursAnimes', 'Vinland Saga', 'vinland saga', null, null, 11),
  ('meilleursAnimes', 'Jujutsu Kaisen', 'jujutsu kaisen', null, null, 12),
  ('meilleursAnimes', 'Demon Slayer: Kimetsu no Yaiba', 'demon slayer kimetsu no yaiba', null, null, 13),
  ('meilleursAnimes', 'Frieren: Beyond Journey''s End', 'frieren beyond journeys end', null, null, 14),
  ('meilleursAnimes', 'Monster', 'monster', null, null, 15),
  ('animeIdiots', 'Naruto Uzumaki', 'naruto uzumaki', null, null, 1),
  ('animeIdiots', 'Son Goku', 'son goku', null, null, 2),
  ('animeIdiots', 'Luffy', 'luffy', null, null, 3),
  ('animeIdiots', 'Mineta', 'mineta', null, null, 4),
  ('animeIdiots', 'Zenitsu Agatsuma', 'zenitsu agatsuma', null, null, 5),
  ('animeIdiots', 'Aqua', 'aqua', null, null, 6),
  ('animeIdiots', 'Kazuma Satou', 'kazuma satou', null, null, 7),
  ('animeIdiots', 'Patrick Star', 'patrick star', null, null, 8),
  ('animeIdiots', 'Mako Mankanshoku', 'mako mankanshoku', null, null, 9),
  ('animeIdiots', 'Ritsu Kageyama', 'ritsu kageyama', null, null, 10),
  ('meilleursCombats', 'Naruto Uzumaki vs Sasuke Uchiha', 'naruto uzumaki vs sasuke uchiha', null, null, 1),
  ('meilleursCombats', 'Gogeta vs Broly', 'gogeta vs broly', null, null, 2),
  ('meilleursCombats', 'Kakashi Hatake vs Obito Uchiha', 'kakashi hatake vs obito uchiha', null, null, 3),
  ('meilleursCombats', 'Goku vs Jiren', 'goku vs jiren', null, null, 4),
  ('meilleursCombats', 'Naruto Uzumaki & Sasuke Uchiha vs Momoshiki Ōtsutsuki', 'naruto uzumaki  sasuke uchiha vs momoshiki otsutsuki', null, null, 5),
  ('meilleursCombats', 'Luffy vs Katakuri', 'luffy vs katakuri', null, null, 6),
  ('meilleursCombats', 'Netero vs Meruem', 'netero vs meruem', null, null, 7),
  ('meilleursCombats', 'Rock Lee vs Gaara', 'rock lee vs gaara', null, null, 8),
  ('meilleursCombats', 'Ichigo Kurosaki vs Ulquiorra Cifer', 'ichigo kurosaki vs ulquiorra cifer', null, null, 9),
  ('meilleursCombats', 'Satoru Gojo vs Ryomen Sukuna', 'satoru gojo vs ryomen sukuna', null, null, 10),
  ('meilleursCombats', 'Goku vs Frieza', 'goku vs frieza', null, null, 11),
  ('meilleursCombats', 'Luffy vs Kaido', 'luffy vs kaido', null, null, 12),
  ('meilleursCombats', 'Yuji Itadori & Aoi Todo vs Mahito', 'yuji itadori  aoi todo vs mahito', null, null, 13),
  ('meilleursCombats', 'Sasuke Uchiha vs Itachi Uchiha', 'sasuke uchiha vs itachi uchiha', null, null, 14),
  ('meilleursCombats', 'Tengen Uzui vs Gyutaro', 'tengen uzui vs gyutaro', null, null, 15),
  ('meilleursCombats', 'Gohan vs Cell', 'gohan vs cell', null, null, 16),
  ('meilleursCombats', 'Ichigo Kurosaki vs Byakuya Kuchiki', 'ichigo kurosaki vs byakuya kuchiki', null, null, 17),
  ('meilleursCombats', 'Jotaro Kujo vs DIO', 'jotaro kujo vs dio', null, null, 18),
  ('meilleursCombats', 'Might Guy vs Madara Uchiha', 'might guy vs madara uchiha', null, null, 19),
  ('meilleursCombats', 'Rengoku vs Akaza', 'rengoku vs akaza', null, null, 20),
  ('meilleursArcs', 'Fourmis Chimères', 'fourmis chimeres', null, null, 1),
  ('meilleursArcs', 'Marineford', 'marineford', null, null, 2),
  ('meilleursArcs', 'Shiganshina', 'shiganshina', null, null, 3),
  ('meilleursArcs', 'Shibuya', 'shibuya', null, null, 4),
  ('meilleursArcs', 'Soul Society', 'soul society', null, null, 5),
  ('meilleursArcs', 'Pain', 'pain', null, null, 6),
  ('meilleursArcs', 'York Shin City', 'york shin city', null, null, 7),
  ('meilleursArcs', 'Wano', 'wano', null, null, 8),
  ('meilleursArcs', 'Freezer', 'freezer', null, null, 9),
  ('meilleursArcs', 'Coalition', 'coalition', null, null, 10),
  ('meilleuresTechniques', 'Kamehameha', 'kamehameha', null, null, 1),
  ('meilleuresTechniques', 'Rasengan', 'rasengan', null, null, 2),
  ('meilleuresTechniques', 'Bankai', 'bankai', null, null, 3),
  ('meilleuresTechniques', 'Genkidama', 'genkidama', null, null, 4),
  ('meilleuresTechniques', 'Getsuga Tenshō', 'getsuga tensho', null, null, 5),
  ('meilleuresTechniques', 'Chidori', 'chidori', null, null, 6),
  ('meilleuresTechniques', 'Ultra Instinct', 'ultra instinct', null, null, 7),
  ('meilleuresTechniques', 'Domain Expansion', 'domain expansion', null, null, 8),
  ('meilleuresTechniques', 'Gear 5', 'gear 5', null, null, 9),
  ('meilleuresTechniques', 'Amaterasu', 'amaterasu', null, null, 10),
  ('meilleuresTransformations', 'Super Saiyan', 'super saiyan', null, null, 1),
  ('meilleuresTransformations', 'Ultra Instinct', 'ultra instinct', null, null, 2),
  ('meilleuresTransformations', 'Super Saiyan 2 Gohan', 'super saiyan 2 gohan', null, null, 3),
  ('meilleuresTransformations', 'Sage Mode', 'sage mode', null, null, 4),
  ('meilleuresTransformations', 'Madara Rikudo', 'madara rikudo', null, null, 5),
  ('meilleuresTransformations', 'Vasto Lorde Ichigo', 'vasto lorde ichigo', null, null, 6),
  ('meilleuresTransformations', 'Gear 5', 'gear 5', null, null, 7),
  ('meilleuresTransformations', 'Baryon Mode', 'baryon mode', null, null, 8),
  ('meilleuresTransformations', 'Gon Adulte', 'gon adulte', null, null, 9),
  ('meilleuresTransformations', 'Mugetsu', 'mugetsu', null, null, 10),
  ('ligueDesChampions', '2000 : Real Madrid', 'real madrid', null, '2000', 1),
  ('ligueDesChampions', '2001 : Bayern Munich', 'bayern munich', null, '2001', 2),
  ('ligueDesChampions', '2002 : Real Madrid', 'real madrid', null, '2002', 3),
  ('ligueDesChampions', '2003 : AC Milan', 'ac milan', null, '2003', 4),
  ('ligueDesChampions', '2004 : FC Porto', 'fc porto', null, '2004', 5),
  ('ligueDesChampions', '2005 : Liverpool', 'liverpool', null, '2005', 6),
  ('ligueDesChampions', '2006 : FC Barcelona', 'fc barcelona', null, '2006', 7),
  ('ligueDesChampions', '2007 : AC Milan', 'ac milan', null, '2007', 8),
  ('ligueDesChampions', '2008 : Manchester United', 'manchester united', null, '2008', 9),
  ('ligueDesChampions', '2009 : FC Barcelona', 'fc barcelona', null, '2009', 10),
  ('ligueDesChampions', '2010 : Inter Milan', 'inter milan', null, '2010', 11),
  ('ligueDesChampions', '2011 : FC Barcelona', 'fc barcelona', null, '2011', 12),
  ('ligueDesChampions', '2012 : Chelsea', 'chelsea', null, '2012', 13),
  ('ligueDesChampions', '2013 : Bayern Munich', 'bayern munich', null, '2013', 14),
  ('ligueDesChampions', '2014 : Real Madrid', 'real madrid', null, '2014', 15),
  ('ligueDesChampions', '2015 : FC Barcelona', 'fc barcelona', null, '2015', 16),
  ('ligueDesChampions', '2016 : Real Madrid', 'real madrid', null, '2016', 17),
  ('ligueDesChampions', '2017 : Real Madrid', 'real madrid', null, '2017', 18),
  ('ligueDesChampions', '2018 : Real Madrid', 'real madrid', null, '2018', 19),
  ('ligueDesChampions', '2019 : Liverpool', 'liverpool', null, '2019', 20),
  ('ligueDesChampions', '2020 : Bayern Munich', 'bayern munich', null, '2020', 21),
  ('ligueDesChampions', '2021 : Chelsea', 'chelsea', null, '2021', 22),
  ('ligueDesChampions', '2022 : Real Madrid', 'real madrid', null, '2022', 23),
  ('ligueDesChampions', '2023 : Manchester City', 'manchester city', null, '2023', 24),
  ('ligueDesChampions', '2024 : Real Madrid', 'real madrid', null, '2024', 25),
  ('ligueDesChampions', '2025 : Paris Saint-Germain', 'paris saintgermain', null, '2025', 26),
  ('ligueDesChampions', '2026 : Paris Saint-Germain', 'paris saintgermain', null, '2026', 27),
  ('ballonDor', '2000 : Luis Figo', 'luis figo', null, '2000', 1),
  ('ballonDor', '2001 : Michael Owen', 'michael owen', null, '2001', 2),
  ('ballonDor', '2002 : Ronaldo Nazário', 'ronaldo nazario', null, '2002', 3),
  ('ballonDor', '2003 : Pavel Nedvěd', 'pavel nedved', null, '2003', 4),
  ('ballonDor', '2004 : Andriy Shevchenko', 'andriy shevchenko', null, '2004', 5),
  ('ballonDor', '2005 : Ronaldinho', 'ronaldinho', null, '2005', 6),
  ('ballonDor', '2006 : Fabio Cannavaro', 'fabio cannavaro', null, '2006', 7),
  ('ballonDor', '2007 : Kaká', 'kaka', null, '2007', 8),
  ('ballonDor', '2008 : Cristiano Ronaldo', 'cristiano ronaldo', null, '2008', 9),
  ('ballonDor', '2009 : Lionel Messi', 'lionel messi', null, '2009', 10),
  ('ballonDor', '2010 : Lionel Messi', 'lionel messi', null, '2010', 11),
  ('ballonDor', '2011 : Lionel Messi', 'lionel messi', null, '2011', 12),
  ('ballonDor', '2012 : Lionel Messi', 'lionel messi', null, '2012', 13),
  ('ballonDor', '2013 : Cristiano Ronaldo', 'cristiano ronaldo', null, '2013', 14),
  ('ballonDor', '2014 : Cristiano Ronaldo', 'cristiano ronaldo', null, '2014', 15),
  ('ballonDor', '2015 : Lionel Messi', 'lionel messi', null, '2015', 16),
  ('ballonDor', '2016 : Cristiano Ronaldo', 'cristiano ronaldo', null, '2016', 17),
  ('ballonDor', '2017 : Cristiano Ronaldo', 'cristiano ronaldo', null, '2017', 18),
  ('ballonDor', '2018 : Luka Modrić', 'luka modric', null, '2018', 19),
  ('ballonDor', '2019 : Lionel Messi', 'lionel messi', null, '2019', 20),
  ('ballonDor', '2021 : Lionel Messi', 'lionel messi', null, '2021', 21),
  ('ballonDor', '2022 : Karim Benzema', 'karim benzema', null, '2022', 22),
  ('ballonDor', '2023 : Lionel Messi', 'lionel messi', null, '2023', 23),
  ('ballonDor', '2024 : Rodri', 'rodri', null, '2024', 24),
  ('ballonDor', '2025 : Ousmane Dembélé', 'ousmane dembele', null, '2025', 25),
  ('jeuxVideo', 'Super Mario Bros.', 'super mario bros', null, null, 1),
  ('jeuxVideo', 'The Legend of Zelda', 'the legend of zelda', null, null, 2),
  ('jeuxVideo', 'Tetris', 'tetris', null, null, 3),
  ('jeuxVideo', 'Minecraft', 'minecraft', null, null, 4),
  ('jeuxVideo', 'Grand Theft Auto V', 'grand theft auto v', null, null, 5),
  ('jeuxVideo', 'Final Fantasy', 'final fantasy', null, null, 6),
  ('jeuxVideo', 'Metal Gear Solid', 'metal gear solid', null, null, 7),
  ('jeuxVideo', 'Half-Life 2', 'halflife 2', null, null, 8),
  ('jeuxVideo', 'The Witcher 3: Wild Hunt', 'the witcher 3 wild hunt', null, null, 9),
  ('jeuxVideo', 'Dark Souls', 'dark souls', null, null, 10),
  ('superHeros', 'Spider-Man', 'spiderman', null, null, 1),
  ('superHeros', 'Batman', 'batman', null, null, 2),
  ('superHeros', 'Superman', 'superman', null, null, 3),
  ('superHeros', 'Iron Man', 'iron man', null, null, 4),
  ('superHeros', 'Joker', 'joker', null, null, 5),
  ('superHeros', 'Captain America', 'captain america', null, null, 6),
  ('superHeros', 'Wolverine', 'wolverine', null, null, 7),
  ('superHeros', 'Wonder Woman', 'wonder woman', null, null, 8),
  ('superHeros', 'Deadpool', 'deadpool', null, null, 9),
  ('superHeros', 'Harley Quinn', 'harley quinn', null, null, 10),
  ('superHeros', 'Thor', 'thor', null, null, 11),
  ('superHeros', 'Hulk', 'hulk', null, null, 12),
  ('superHeros', 'Flash', 'flash', null, null, 13),
  ('superHeros', 'Black Panther', 'black panther', null, null, 14),
  ('superHeros', 'Thanos', 'thanos', null, null, 15),
  ('superHeros', 'Doctor Doom', 'doctor doom', null, null, 16),
  ('superHeros', 'Green Lantern', 'green lantern', null, null, 17),
  ('superHeros', 'Magneto', 'magneto', null, null, 18),
  ('superHeros', 'Aquaman', 'aquaman', null, null, 19),
  ('superHeros', 'Darkseid', 'darkseid', null, null, 20),
  ('rapFrUs', 'Tupac Shakur', 'tupac shakur', null, null, 1),
  ('rapFrUs', 'The Notorious B.I.G.', 'the notorious big', null, null, 2),
  ('rapFrUs', 'Jay-Z', 'jayz', null, null, 3),
  ('rapFrUs', 'Eminem', 'eminem', null, null, 4),
  ('rapFrUs', 'IAM', 'iam', null, null, 5),
  ('rapFrUs', 'Nas', 'nas', null, null, 6),
  ('rapFrUs', 'Booba', 'booba', null, null, 7),
  ('rapFrUs', 'Kendrick Lamar', 'kendrick lamar', null, null, 8),
  ('rapFrUs', 'NTM', 'ntm', null, null, 9),
  ('rapFrUs', 'Dr. Dre', 'dr dre', null, null, 10),
  ('rapFrUs', 'MC Solaar', 'mc solaar', null, null, 11),
  ('rapFrUs', 'Soprano', 'soprano', null, null, 12),
  ('rapFrUs', 'Snoop Dogg', 'snoop dogg', null, null, 13),
  ('rapFrUs', 'Kaaris', 'kaaris', null, null, 14),
  ('rapFrUs', 'Lil Wayne', 'lil wayne', null, null, 15),
  ('trouveAnime', 'One Piece', 'one piece', '🏴‍☠️👒🍖', null, 1),
  ('trouveAnime', 'Naruto', 'naruto', '🦊🍥🍃', null, 2),
  ('trouveAnime', 'Dragon Ball', 'dragon ball', '🐉⚡🥋', null, 3),
  ('trouveAnime', 'Demon Slayer', 'demon slayer', '👹⚔️🌸', null, 4),
  ('trouveAnime', 'Jujutsu Kaisen', 'jujutsu kaisen', '🤛👻⚫', null, 5),
  ('trouveAnime', 'Attack on Titan', 'attack on titan', '🧱🩸👹', null, 6),
  ('trouveAnime', 'Death Note', 'death note', '📓🍎💀', null, 7),
  ('trouveAnime', 'Fullmetal Alchemist: Brotherhood', 'fullmetal alchemist brotherhood', '🧪⚗️🤖', null, 8),
  ('trouveAnime', 'Hunter × Hunter', 'hunter  hunter', '🕷️🃏🎣', null, 9),
  ('trouveAnime', 'Bleach', 'bleach', '👒⚔️🔥', null, 10),
  ('trouveAnime', 'My Hero Academia', 'my hero academia', '🧊🔥🏫', null, 11),
  ('trouveAnime', 'Haikyuu!!', 'haikyuu', '🏐🦅🏆', null, 12),
  ('trouveAnime', 'Fate/Zero', 'fatezero', '⚔️🏺👑', null, 13),
  ('trouveAnime', 'Your Lie in April', 'your lie in april', '🎹🎻💙', null, 14),
  ('trouveAnime', 'Neon Genesis Evangelion', 'neon genesis evangelion', '🤖🌎❤️', null, 15),
  ('devinePersonnage', 'Naruto Uzumaki', 'naruto uzumaki', '🍜 Rêve de devenir Hokage.', null, 1),
  ('devinePersonnage', 'Monkey D. Luffy', 'monkey d luffy', '🍖 Veut devenir le Roi des Pirates.', null, 2),
  ('devinePersonnage', 'Son Goku', 'son goku', '🟠 Devient plus fort après chaque combat.', null, 3),
  ('devinePersonnage', 'Roronoa Zoro', 'roronoa zoro', '⚔️ Porte trois sabres.', null, 4),
  ('devinePersonnage', 'Gojo Satoru', 'gojo satoru', '⚡ Possède les Six Yeux.', null, 5),
  ('devinePersonnage', 'Light Yagami', 'light yagami', '📓 Tue en écrivant des noms.', null, 6),
  ('devinePersonnage', 'L', 'l', '🍎 Adore les pommes et enquête sur Kira.', null, 7),
  ('devinePersonnage', 'Naruto Uzumaki', 'naruto uzumaki', '🦊 Possède Kyûbi en lui.', null, 8),
  ('devinePersonnage', 'Itachi Uchiha', 'itachi uchiha', '🔥 Son frère s''appelle Sasuke.', null, 9),
  ('devinePersonnage', 'Tanjiro Kamado', 'tanjiro kamado', '⚔️ A perdu sa famille à cause des démons.', null, 10),
  ('devinePersonnage', 'Inosuke Hashibira', 'inosuke hashibira', '🐗 Porte un masque de sanglier.', null, 11),
  ('devinePersonnage', 'Zenitsu Agatsuma', 'zenitsu agatsuma', '⚡ Dort pour devenir très puissant.', null, 12),
  ('devinePersonnage', 'Saitama', 'saitama', '👊 Peut battre n''importe qui d''un seul coup.', null, 13),
  ('devinePersonnage', 'Gon Freecss', 'gon freecss', '🕷️ Utilise une canne à pêche comme arme.', null, 14),
  ('devinePersonnage', 'Killua Zoldyck', 'killua zoldyck', '⚡ Est un assassin de la famille Zoldyck.', null, 15),
  ('devinePersonnage', 'Eren Yeager', 'eren yeager', '🩸 Cherche à exterminer les Titans.', null, 16),
  ('devinePersonnage', 'Mikasa Ackerman', 'mikasa ackerman', '🧣 Porte toujours une écharpe rouge.', null, 17),
  ('devinePersonnage', 'Obito Uchiha', 'obito uchiha', '🎭 Cache son identité derrière un masque orange.', null, 18),
  ('devinePersonnage', 'Lelouch Lamperouge', 'lelouch lamperouge', '👑 Dirige Britannia avec le Geass.', null, 19),
  ('devinePersonnage', 'Edward Elric', 'edward elric', '⚗️ A perdu un bras et une jambe en voulant ressusciter sa mère.', null, 20),
  ('animeParOrganisation', 'Naruto', 'naruto', 'Akatsuki', null, 1),
  ('animeParOrganisation', 'One Piece', 'one piece', 'Marine', null, 2),
  ('animeParOrganisation', 'One Piece', 'one piece', 'Chapeaux de Paille', null, 3),
  ('animeParOrganisation', 'Hunter × Hunter', 'hunter  hunter', 'Phantom Troupe', null, 4),
  ('animeParOrganisation', 'Attack on Titan', 'attack on titan', 'Survey Corps (Bataillon d''Exploration)', null, 5),
  ('animeParOrganisation', 'Bleach', 'bleach', 'Gotei 13', null, 6),
  ('animeParOrganisation', 'Bleach', 'bleach', 'Espada', null, 7),
  ('animeParOrganisation', 'My Hero Academia', 'my hero academia', 'Hero Association / Villain League', null, 8),
  ('animeParOrganisation', 'The Seven Deadly Sins', 'the seven deadly sins', 'Ten Commandments', null, 9);
